### ISSUE TITLE
banner images does not appear

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/coi.research.uiowa.edu#11]
Coming from http://projects.sitenow.uiowa.edu/projects/research-ovpred/tasks/377

New banner images uploaded through the OVPRED Compliance Theme configuration interface do not appear when the configurations are saved. The default images stays selected.

Issue #6 should happen first (those modules/themes have been added to custom profile, so those modules should be removed from this repo and this update should happen against the custom profile)

**Comment by adamdelaney** [comment]
I cannot replicate this issue.
