### ISSUE TITLE
pattern overlay dots

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/coi.research.uiowa.edu#12]
The option to toggle the pattern overlay dots on and off is no longer present.
(https://researchcoi.stage.drupal.uiowa.edu//sites/coi.research.uiowa.edu/themes/ovpred_compliance/assets/images/textures/dot-pattern.png )

Issue #6 should happen first (those modules/themes have been added to custom profile, so those modules should be removed from this repo and this update should happen against the custom profile)

**Comment by adamdelaney** [comment]
See custom profile commit: 43f1dd6fe9b64e9214170a7cc560706d1fe17b64
