### ISSUE TITLE
Configuration options for menu background

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/coi.research.uiowa.edu#4]
Select list of predefined options. Preprocess in a class on the page.

On a custom config form that we can give webmasters access to.

Related to #5.

**Comment by brandonneil** [comment]
Maybe it is one set of configuration, a combination of #4 and #5, e.g:

-Yellow background, black text
- Black background, light text
... etc.

I think we should get confirmation from modei about what options they want. For now, let's theme an initial style based on what @adamdelaney thinks looks good.

**Comment by adamdelaney** [comment]
This config option lives in ovpred_compliance_theme module.

**Comment by adamdelaney** [comment]
We need more info from the client.
